# -*- coding: utf-8 -*-
"""HW2_hash_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15x78Ph7Q3RIF3-J1eXpxFTwEostAEZVS
"""

import matplotlib.pyplot as plt

from google.colab import drive
import pandas as pd
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/hw2/hw2_data.txt'


# Step 1: 讀取資料
word_count = {}

with open('/content/drive/MyDrive/hw2/hw2_data.txt', "r") as file:
    for line in file:
        word = line.strip()
        if word in word_count:
            word_count[word] += 1
        else:
            word_count[word] = 1

# Step 2: 輸出不重複單字數
print(f"不重複英文字總數: {len(word_count)}")

# Step 3: 輸出每個字的出現次數
print("每個字的出現次數如下：")
for word, count in word_count.items():
    print(f"{word}: {count}")

# Step 4: 依出現次數排序，準備畫圖
sorted_words = sorted(word_count.items(), key=lambda x: x[1], reverse=True)
words = [item[0] for item in sorted_words]
counts = [item[1] for item in sorted_words]

# Step 5: 畫出直方圖
plt.figure(figsize=(12, 6))
plt.bar(words, counts)
plt.xticks(rotation=90)
plt.title("英文字出現頻率直方圖")
plt.xlabel("英文字")
plt.ylabel("出現次數")
plt.tight_layout()
plt.savefig("result.png")
plt.show()